### ISSUE TITLE
Hardfault: Bus fault on vector table read (stm32f103ret6) on a dronecan node

### ISSUE THREAD

**Issue by dirksavage88** [PX4/NuttX#215]
This is a dronecan application firmware that is hard faulting after the bootloader updates firmware (there is nothing occupying flash space after the bootloader). The near exact board config worked with an stm32f103zet6 prototype (only differences is that there is no fsmc, and only 1 memory region on the ret6) and I was able to get the dronecan node operational and a nuttx console going.

The board config can be found here: https://github.com/PX4/PX4-Autopilot/compare/main...dirksavage88:Firmware:aa_cannode_v1

Dronecan bootloader works as intended and I see it come up in init mode, it allows me to update the firmware via the dronecan gui tool. I also verify node status and node info when I plug in the node flashed with the bootloader. With the hardfault, it doesn't recover and the bootloader doesn't jump into firmware enough for me to get a system console (it just restarts and the node comes back up in init).

See screen snips. I am reading the hardfault in the bus monitor ascii section. 

@ryanjAA

@davids5 I believe this is similar to oliminexino stm32 you brought into Nuttx, it's just a higher density version (512kb flash, 64kb sram).

Other known issues: the nuttx hardware pinmap for the stm32f103r is missing uart4 & uart5. I've made these changes in my local nuttx submodule but it is not fixed upstream. The node has a sensor on uart4.

![hardfault1](https://user-images.githubusercontent.com/35986980/212788247-e19f7768-fbe9-4f43-a9bb-1377d911e9a5.png)
![hardfault2](https://user-images.githubusercontent.com/35986980/212788248-0ec1b2b8-3acb-47fd-a6cc-512ec371df78.png)
![hardfault3](https://user-images.githubusercontent.com/35986980/212788254-cf7bcfc2-4f2b-4c4d-aefa-cb9d4b340e3e.png)

**Comment by davids5** [comment]
Some references

The Olimex Can node was running a STM32F103RBT6 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1945821/213440713-225717c3-e5e4-4f6b-87ba-a2408f4262eb.png">


The  STM32F103RET6 and the STM32F103ZET6 differ in pin and flash size

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1945821/213440236-a75a2659-0777-44a1-8a86-062119ddb656.png">

**Comment by dirksavage88** [comment]
I've expanded the flash param storage, so the app now starts at 8000 (instead of 5000). Updated the script.ld as well as the boot_config file to reflect the expanded parameter flash.

Now with the symbols loaded, it looks like it hangs on the LSE:
![add_symbols](https://user-images.githubusercontent.com/35986980/213717674-5453ae17-8b1a-4062-82cf-9e3f0dfeddc4.png)
![debug](https://user-images.githubusercontent.com/35986980/213717678-24d66d8b-2e36-4872-861e-2dca67920609.png)
![readelf](https://user-images.githubusercontent.com/35986980/213717682-9ace54c4-a8c2-4233-aaef-0b173a6695cf.png)

**Comment by davids5** [comment]
I would bet the board does not have and LSE (Low speed crystal) or it is not starting

**Comment by dirksavage88** [comment]
No LSE on the node. It was on the prototype board and hence why existing kconfig was giving us issues. Disabled RTC driver completely and now it's operational. Thanks for the help @davids5!
