### ISSUE TITLE
Update master to a newer upstream version

### ISSUE THREAD

**Issue by ghulands** [PX4/NuttX#45]
I am looking to port PX4 over to a board with the tm4c line of MCU's but the master branch doesn't contain the tiva arch folder or the tm4c launchpad configs. It would be good if you can move it over to the master branch.

**Comment by LorenzMeier** [comment]
Please use the nuttx_next branch of PX4/Firmware, which holds what you're looking for. The port would be very welcome!

https://github.com/px4/firmware/tree/nuttx_next
