### ISSUE TITLE
Upstream Important changes to add to 7.27 or Bump to 7.28

### ISSUE THREAD

**Issue by davids5** [PX4/NuttX#47]
https://bitbucket.org/nuttx/apps/pull-requests/167/apps-nshlib-fix-buffer-overrun-when?link_source=email

**Comment by dagar** [comment]
Branch for 7.28+ https://github.com/PX4/NuttX/tree/px4_firmware_nuttx-7.28%2B

**Comment by dagar** [comment]
Moved to 7.28 - https://github.com/PX4/Firmware/pull/11256
