### ISSUE TITLE
stm32f7 serial TX DMA

### ISSUE THREAD

**Issue by dagar** [PX4/NuttX#55]
https://bitbucket.org/nuttx/nuttx/pull-requests/858/arch-arm-src-stm32f7-stm32_serialc-add-dma/diff

**Comment by dagar** [comment]
Is there an opinionated version of this we could carry in tree until something is ready upstream?
For PX4 simply having TX DMA on a single UART (telem 2) for fmu-v5 (and v5x) would provide the majority of the benefit.

**Comment by davids5** [comment]
The above PR was completed by PX4 and was upstreamed and backported  in https://github.com/PX4/NuttX/commit/32f758f0e96c8dd7ec29cffa526dbad50ec51fec
