### ISSUE TITLE
Return before close ELF fd!

### ISSUE THREAD

**Issue by ultrasystem** [PX4/NuttX#66]
elf_init open a elf file , if both enabled CONFIG_NSH_BUIlTAPPS and CONFIG_NSH_FILE_APPS , elf_init will read elf file in /bin directory, but that length is zero , elf_read failed return and NOT close elf fd, so this line MUST be return to errout_with_init

https://github.com/PX4/NuttX/blob/feb5b6f1743fc3376008013f7dbd16dbc8501f10/binfmt/elf.c#L238

**Comment by davids5** [comment]
Wating on upstream https://github.com/apache/incubator-nuttx/pull/3670

**Comment by davids5** [comment]
Closed by https://github.com/PX4/NuttX/pull/152
