### ISSUE TITLE
Feature Request: Bring NuttX/apps/interpreters/micropython into master

### ISSUE THREAD

**Issue by davidbuzz** [PX4/NuttX#67]
micropython as a scripting language for UAVs has a lot of potential, and bringing it into the 'master' branch would allow developers to try-out this.

**Comment by nuttx** [comment]
Already available in upstream NuttX: https://bitbucket.org/nuttx/apps/src/master/interpreters/micropython

**Comment by davids5** [comment]
@davidbuzz this would be on nuttx_next as it tracks upstream nuttx. I am not sure if it would backport to master due to it's age but a PR would be welcome

@LorenzMeier

**Comment by davidbuzz** [comment]
I know these things are hard to estimate, but would it be possible to estimate when nuttx_next is likely/possibly going to become master? 1month, 6months, a year?
