### ISSUE TITLE
Bug: Break frame not working properly on stm32f4 U(S)ART

### ISSUE THREAD

**Issue by teancake** [PX4/NuttX#71]
I am using an SRF01 ultrasonic rangefinder (http://www.robot-electronics.co.uk/htm/srf01tech.htm) with PIXHAWK. The rangefinder has a single-wire serial connection which can be connected to the TX pin of a U(S)ART port when the port is configured into single-wire mode. The problem is that the SRF01 requires a break frame (>=12 bits) prior each measurement. The following code is used to send the break frame and it simply does not work.

ioctl(fd_UART, TIOCSBRK,0);
usleep(2000);
ioctl(fd_UART, TIOCCBRK,0);

in which the fd_UART is the file descriptor of the UART.

Because of this, I found that the stm32 serial driver in nuttx was not implemented properly for the 'break frame' and the following is the description.

In file Nuttx/nuttx/arch/arm/src/stm32/stm32_serial.c, from line 1908 to 1927, the code is as follows.
# ifdef CONFIG_USART_BREAKS

```
case TIOCSBRK:  /* BSD compatibility: Turn break on, unconditionally */
  {
    irqstate_t flags = irqsave();
    uint32_t cr2 = up_serialin(priv, STM32_USART_CR2_OFFSET);
    up_serialout(priv, STM32_USART_CR2_OFFSET, cr2 | USART_CR2_LINEN);
    irqrestore(flags);
  }
  break;

case TIOCCBRK:  /* BSD compatibility: Turn break off, unconditionally */
  {
    irqstate_t flags;
    flags = irqsave();
    uint32_t cr1 = up_serialin(priv, STM32_USART_CR2_OFFSET);
    up_serialout(priv, STM32_USART_CR2_OFFSET, cr2 & ~USART_CR2_LINEN);
    irqrestore(flags);
  }
  break;
```
# endif

First, there is a typo in this code on line 1922, i.e. 
        uint32_t cr1 = up_serialin(priv, STM32_USART_CR2_OFFSET);
cr1 should be cr2. Then, according to the Reference Manual of STM32F4XX MCUs (http://www.st.com/st-web-ui/static/active/cn/resource/technical/document/reference_manual/DM00031020.pdf, page 1004,1005), two registers CR1 and CR2 are needed in order for the UART to send the break frame. Specifically, the SBK bit in CR1 and the LINEN bit in CR2 should be used together. Apperantly, the above code only set/unset the LINEN bit in CR2. 

The modified code is as follows and with it the SRF01 sensor functions properly.
# ifdef CONFIG_USART_BREAKS

```
case TIOCSBRK:  /* BSD compatibility: Turn break on, unconditionally */
  {
    irqstate_t flags = irqsave();
    uint32_t cr1 = up_serialin(priv, STM32_USART_CR1_OFFSET);
    up_serialout(priv, STM32_USART_CR1_OFFSET, cr1 | USART_CR1_SBK);
    uint32_t cr2 = up_serialin(priv, STM32_USART_CR2_OFFSET);
    up_serialout(priv, STM32_USART_CR2_OFFSET, cr2 | USART_CR2_LINEN);
    irqrestore(flags);
  }
  break;

case TIOCCBRK:  /* BSD compatibility: Turn break off, unconditionally */
  {
    irqstate_t flags;
    flags = irqsave();
    uint32_t cr1 = up_serialin(priv, STM32_USART_CR1_OFFSET);
    up_serialout(priv, STM32_USART_CR1_OFFSET, cr1 & ~USART_CR1_SBK);
    uint32_t cr2 = up_serialin(priv, STM32_USART_CR2_OFFSET);
    up_serialout(priv, STM32_USART_CR2_OFFSET, cr2 & ~USART_CR2_LINEN);
    irqrestore(flags);
  }
  break;
```
# endif

Could anyone help to check whether the problem exists and whether my modification to the original code is reasonable? Thanks.

Further more, since the above code is within a macro definition CONFIG_USART_BREAKS, this definition should be added in the configuration file nuttx-configs/px4fmu-v2/nsh/defconfig, I put it after line 315 as
CONFIG_USART_BREAKS=y

This is also the reason why the typo in the original code was not found by the compiler. Due to the falsehood of the definition of CONFIG_USART_BREAKS, this section of code is eliminated by the preprocessor and not compiled.

Thanks very much.

All the best
Xiaoke Yang
das.xiaoke@hotmail.com

**Comment by davids5** [comment]
@teancake

Please submit a Pull request.

However I think that disabling LIN mode in the IOCTL is not a good Idea.  

Also keep in mind:

The duration of the break, and the Note below 

![image](https://cloud.githubusercontent.com/assets/1945821/15045997/57682098-1279-11e6-8781-e101a8609004.png)

**Comment by teancake** [comment]
I see what you mean. Actually if I reduce the time delay in between the two IOCTLs to a certain level, the SRF01 sensor won't respond, which suggests that the break frame is not sent. 

And, if the IOCTL disabling LIN mode is commented out, the sensor still works properly which is an indication that the the SBK bit has been reset. Thanks for your suggestions.

As for the duration of the break, in LIN mode the length is 13-bit, instead of 10/11 bit in the ordinary mode. See page 985 of the manual.

Cheers
