### ISSUE TITLE
stdint minimum values are positive

### ISSUE THREAD

**Issue by jschall** [PX4/NuttX#83]

**Comment by julianoes** [comment]
I checked `INT8_MIN` and it seems to be correct, so `-128`:
https://github.com/PX4/NuttX/blob/master/nuttx/include/stdint.h#L58

**Comment by jschall** [comment]
No it is not. The binary value is correct *if and only if* the value is loaded into an 8-bit signed integer. If you are trying to, for example, constrain a floating point number prior to conversion to an 8-bit integer, it is utterly wrong.

**Comment by julianoes** [comment]
Ah, I see what you mean. In that case you're right.

**Comment by davids5** [comment]
@jschall 

The defines are correct in upstream NuttX - and therefore on the nuttx_v3 branch of Firmware.

@LorenzMeier  do you want me to  backport the file or just wait until nuttx_v3  replaces master?
