### ISSUE TITLE
Buffer overrun possible in NuttShell

### ISSUE THREAD

**Issue by chungkim** [PX4/NuttX#84]
At lines 151 and 155 of apps/nshlib/nsh_fscmds.c (master branch), nsh_getdirpath can overflow the global buffer, g_iobuffer, when the lengths of the two user-specified arguments (path, and file) are longer than the predefined IOBUFFERSIZE.  Maybe use snprintf, instead of sprintf?

**Comment by nuttx** [comment]
Fixed in upstream NuttX with commit 9b951b4dd8502532ad8e8703230dfc69ca4c876d

Thanks!
