### ISSUE TITLE
Flashing nuttx to pixhawk 2.4.8

### ISSUE THREAD

**Issue by amitmanish** [PX4/NuttX#91]
I am trying to understand px4 firmware. So i was thinking to flash nuttx on pixhawk but i could not found px4fmu-v2/nsh board in nuttx. Could anyone also help in in understanding how px4 firmware files are executed by nuttx. Thanks in advance.

**Comment by julianoes** [comment]
The PX4 modules and the NuttX OS are also compiled and linked in the PX4/Firmware project. If you disabled all PX4 modules and drivers, you would be left with more or less plain NuttX.

**Comment by amitmanish** [comment]
Thanks for reply julianoes, but i wanted to start from scratch understanding how px4 scripts are execueted in  nuttx in realtime. I see px4 cmake files configure nuttx like for pixhawk during building px4. I want to do the same manually.

**Comment by julianoes** [comment]
> how px4 scripts are execueted in nuttx in realtime

The PX4 modules and drivers are built into the firmware image together with NuttX. The startup scripts are parsed in the NuttShell (nsh) on startup.

If you want to start from scratch you can start with plain [NuttX](http://www.nuttx.org/) and then get inspiration how the integration is done for PX4.

**Comment by amitmanish** [comment]
Thanks. I will now start from scratch.

**Comment by amitmanish** [comment]
Can i add px4fmu-v2 board to nuttx so that i can configure it using make menuconfig.

**Comment by julianoes** [comment]
I don't know. I have not worked on these basic stuff since 2012, sorry. I'll close this issue now, please re-open if you have a specific question to the current NuttX and PX4 implementation.

**Comment by dagar** [comment]
@amitmanish PX4's NuttX build is tightly integrated. It's a regular nuttx config, but all the board init lives outside of the NuttX build system.

Working from PX4 you there are helpers for menuconfig.
`make px4fmu-v2_default menuconfig`
`make px4fmu-v2_default qconfig`

**Comment by LorenzMeier** [comment]
@dagar do we have that documented in the dev guide?

**Comment by amitmanish** [comment]
Thanks daggar.

**Comment by hamishwillee** [comment]
> @dagar do we have that documented in the dev guide?

See https://github.com/PX4/Devguide/pull/444
